basket_rencontre_homepage:
    path:     /rencontreDom/index
    defaults: { _controller: BasketRencontreBundle:Rencontre:index }
    
basket_rencontreext:
    path:   /rencontreExt/index
    defaults: {_controller: BasketRencontreBundle:RencontreExt:index}
