basket_homepage:
    pattern: /
    defaults: {_controller: BasketPlayerBundle:player:homepage}

basket_equipe:
    resource: "@BasketEquipeBundle/Resources/config/routing.yml"
    prefix:   /

basket_rencontre:
    resource: "@BasketRencontreBundle/Resources/config/routing.yml"
    prefix:   /

basket_entrainement:
    resource: "@BasketEntrainementBundle/Resources/config/routing.yml"
    prefix:   /

basket_player:
    resource: "@BasketPlayerBundle/Resources/config/routing.yml"
    prefix:   /

basket_database:
    resource: "@BasketDatabaseBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

