basket_entrainement:
    resource: "@BasketEntrainementBundle/Resources/config/routing.yml"
    prefix:   /

basket_player:
    resource: "@BasketPlayerBundle/Resources/config/routing.yml"
    prefix:   /

basket_database:
    resource: "@BasketDatabaseBundle/Resources/config/routing.yml"
    prefix:   /

