<?php

namespace Basket\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntrainementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrainementRepository extends EntityRepository
{
}
