<?php

namespace Basket\DatabaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RencontreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RencontreRepository extends EntityRepository
{
}
